import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "./context/authContext";

const kanit = Kanit({ subsets: ["latin"], weight: "200" });
export const metadata: Metadata = {
  title: "College admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <AuthContextProvider>
          <Toaster position="top-center"></Toaster>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
