import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/authContext";
import { Toaster as HotToaster } from "react-hot-toast";
import { Toaster as UiToaster } from "@/components/ui/toaster";
import { ThemeProvider } from "./components/ui/theme-provider";

const kanit = Kanit({ subsets: ["latin"], weight: "200" });
export const metadata: Metadata = {
  title: "College admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <AuthContextProvider>
        <ThemeProvider>

          <HotToaster position="top-center" />
          <UiToaster />
          {children}
        </ThemeProvider>
        </AuthContextProvider>

      </body>
    </html>
  );
}
